# https://dev.to/michi/publish-to-npm-automatically-with-github-actions-5805
# https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-nodejs-packages

name: publish-jupyterlab_robotmode

on:
  release:
    types: [created]

defaults:
  run:
    working-directory: src/jupyterlab_robotmode

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@robocorp'
    - run: pip install jupyter-packaging jupyterlab==3.0.0.rc10 setuptools wheel
    - run: python setup.py bdist_wheel
    - run: |
        npm ci
        git config --global user.name "release-jupyterlab_robotmode"
        git config --global user.email "release-jupyterlab_robotmode@example.com"
        npm version ${{ github.event.release.tag_name }} --allow-same-version
        npm run build
        npm publish
      working-directory: publish-robotmode
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
